import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const ctx = {window: {}};
vm.createContext(ctx);
const filename = new URL('../src/runtime/sakurayo-command.js', import.meta.url);
assert.ok(fs.existsSync(filename), 'command lobby module must exist');
vm.runInContext(fs.readFileSync(filename, 'utf8'), ctx);
const C = ctx.window.SakurayoCommand;
const old = {coins: 50, done: [1], runs: 1, kills: 10, shop40: {ops: {pity: 12, owned: {sayo_echo: 2}}}};
const original = JSON.stringify(old);
assert.equal(C.inbox(old).filter(x => x.ready).length, 2);
assert.equal(JSON.stringify(old), original, 'reading inbox must not mutate save');
assert.equal(C.claimSupply(old, 'chapter2').reason, 'locked');
assert.equal(old.coins, 50);
assert.equal(C.claimSupply(old, 'chapter1').ok, true);
assert.equal(old.coins, 230);
assert.equal(old.shop40.ops.pity, 12);
assert.equal(old.shop40.ops.owned.sayo_echo, 2);
assert.equal(C.claimSupply(old, 'chapter1').reason, 'claimed');
assert.equal(old.coins, 230);
const reloaded = JSON.parse(JSON.stringify(old));
assert.equal(C.claimSupply(reloaded, 'chapter1').ok, false);
assert.equal(C.claimSupply(reloaded, 'unknown').reason, 'unknown');
const legacy = {coins: 5, runs: 1};
assert.equal(C.claimSupply(legacy, 'firstRun').ok, true);
assert.equal(legacy.coins, 125);
assert.equal(C.inbox({done: [1,1],runs:0}).filter(x=>x.ready).length, 1);
assert.equal(C.inbox({done:[1,2,3,4],runs:1,kills:500}).filter(x=>x.ready).length, 6);
vm.runInContext(fs.readFileSync(new URL('../src/runtime/sakurayo-lobby.js', import.meta.url), 'utf8'), ctx);
reloaded.shop40 = ctx.window.SakurayoLobby.normalizeOps(reloaded.shop40);
assert.equal(C.claimSupply(reloaded, 'chapter1').reason, 'claimed', 'lobby migration must preserve supply receipts');
console.log('PASS command unit: legacy save, finite milestones, locked/duplicate claims, persistence');
