import assert from 'node:assert/strict';
import path from 'node:path';
import fs from 'node:fs';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {chromium} from 'playwright';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const entry=process.env.SAKURAYO_ENTRY||process.argv[2]||'src/index.html';
const browser=await chromium.launch({headless:true});
try {
  const page=await browser.newPage({viewport:{width:932,height:430}}),errors=[];
  page.on('pageerror',error=>errors.push(String(error)));
  await page.goto(pathToFileURL(path.resolve(root,entry)).href+'?test=1');
  await page.waitForFunction(()=>window.SakurayoPlatform&&window.__SAKURAYO_TEST__);
  const api=(method,...args)=>page.evaluate(({method,args})=>window.__SAKURAYO_TEST__[method](...args),{method,args});
  const back=()=>page.evaluate(()=>window.SakurayoPlatform.back());
  const state=()=>page.evaluate(()=>window.__SAKURAYO_TEST__.snapshot().mode);
  assert.equal(await back(),false,'main lobby delegates exit to Android');
  await page.locator('#menu [data-open="roster"]').first().click();
  await page.locator('#rosterWall46 [data-card]').first().click();
  assert.equal(await back(),true);assert.equal(await page.locator('#rosterPeek46').count(),0);
  assert.equal(await page.locator('#rosterDrawer').isVisible(),true,'native return closes top detail first');
  await back();assert.equal(await page.locator('#rosterDrawer').isVisible(),false);
  await api('start');
  if(await page.locator('#tutorialSkip37').isVisible())await page.locator('#tutorialSkip37').click();
  if(await state()==='menu')await api('start');
  assert.equal(await state(),'dialogue');await back();assert.equal(await page.locator('#dialogue').isVisible(),true,'native return advances opening dialogue');
  await api('dismissDialogue');assert.equal(await state(),'play');
  await back();assert.equal(await state(),'pause');await back();assert.equal(await state(),'play');
  await api('triggerUpgrade');assert.equal(await state(),'level');await back();assert.equal(await state(),'level','native return cannot discard upgrade');
  await api('chooseUpgrade',0);
  await page.keyboard.down('d');
  await page.evaluate(()=>window.SakurayoPlatform.suspend());assert.equal(await state(),'pause');
  await page.evaluate(()=>window.SakurayoPlatform.resume());assert.equal(await state(),'pause','battle requires manual resume');
  await back();const before=await api('snapshot');await page.evaluate(()=>window.advanceTime(200));const after=await api('snapshot');
  assert.equal(after.player.x,before.player.x,'native suspend releases held combat key');
  await page.keyboard.up('d');
  await api('finish',false);assert.equal(await state(),'result');await back();assert.equal(await state(),'menu');
  const opened=await api('openExploration41',1);assert.equal(opened.opened,true);
  await page.keyboard.down('d');await page.waitForTimeout(80);
  await page.evaluate(()=>window.SakurayoPlatform.suspend());const paused=await api('snapshot');await page.waitForTimeout(150);const still=await api('snapshot');
  assert.equal(still.extensions.exploration.x,paused.extensions.exploration.x,'exploration RAF stops in background');
  await page.evaluate(()=>window.SakurayoPlatform.resume());await page.waitForTimeout(100);const resumed=await api('snapshot');
  assert.equal(resumed.extensions.exploration.x,paused.extensions.exploration.x,'exploration resumes without held key or elapsed-time jump');
  await page.keyboard.up('d');await back();assert.equal(await page.locator('#exploration41').isVisible(),false);await back();
  // Use each real export button with the Android interface seam.
  await page.evaluate(()=>{window.platformExports=[];window.SakurayoAndroid={exportJson:(name,text)=>window.platformExports.push({name,text})};});
  await api('openSaveManager');await page.locator('#downloadSave38').click();await back();
  await page.locator('#commandSettings47').click();await page.locator('#commandStats48').click();await page.locator('#downloadAnalytics37').click();
  const exports=await page.evaluate(()=>window.platformExports);assert.equal(exports.length,2);assert.ok(exports[0].name.endsWith('.json'));assert.equal(JSON.parse(exports[0].text).character,'sayo');assert.ok(JSON.parse(exports[1].text).summary);
  assert.deepEqual(errors,[]);
  fs.mkdirSync(path.join(root,'tests/artifacts/platform'),{recursive:true});
  await page.screenshot({path:path.join(root,'tests/artifacts/platform/platform.png')});
  console.log('platform_smoke PASS: real native-back routes, suspend inputs/RAF, stats/save export buttons');
} finally {await browser.close();}
