import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
const ctx={window:{}};vm.createContext(ctx);
const file=new URL('../src/runtime/sakurayo-services.js',import.meta.url);
assert.ok(fs.existsSync(file),'offline mailbox and login services must exist');
for(const name of ['services','command','lobby'])vm.runInContext(fs.readFileSync(new URL('../src/runtime/sakurayo-'+name+'.js',import.meta.url),'utf8'),ctx);
const S=ctx.window.SakurayoServices,C=ctx.window.SakurayoCommand,L=ctx.window.SakurayoLobby;
const save={coins:0,runs:1,done:[1],shop40:{ops:{pity:9}}};
const before=JSON.stringify(save);
assert.equal(S.mailbox(save,C).length,3);
assert.equal(JSON.stringify(save),before,'mailbox reads never mutate saves');
assert.equal(S.markRead(save,'welcome',C),true);
assert.equal(S.mailbox(save,C)[0].read,true);
assert.equal(S.claimMail(save,'chapter2',C).reason,'unknown');
assert.equal(S.claimMail(save,'welcome',C).reward,200);
assert.equal(S.claimMail(save,'welcome',C).reason,'claimed');
assert.equal(S.claimMail(save,'chapter1',C).reward,180);
assert.equal(C.claimSupply(save,'chapter1').reason,'claimed','mail and task share one receipt');
assert.equal(S.claimAll(save,C).reward,120);
assert.equal(S.claimAll(save,C).reward,0);
assert.equal(save.coins,500);
save.shop40=L.normalizeOps(save.shop40);
assert.equal(S.mailbox(save,C).every(m=>m.read&&m.claimed),true,'read and receipt flags survive migration');
assert.equal(save.shop40.ops.pity,9);
assert.equal(S.markRead(save,'__proto__',C),false);
const login={coins:0};
const date=s=>new Date(s+'T12:00:00');
assert.equal(S.claimLogin(login,date('2026-10-05')).reward,60);
assert.equal(S.claimLogin(login,date('2026-10-05')).reason,'claimed');
assert.equal(S.claimLogin(login,date('2026-10-04')).reason,'clock');
for(let day=6;day<=11;day++)assert.equal(S.claimLogin(login,date('2026-10-'+String(day).padStart(2,'0'))).ok,true);
assert.equal(login.coins,900);
assert.equal(S.claimLogin(login,date('2026-10-12')).reason,'complete');
login.shop40=L.normalizeOps(login.shop40);
assert.equal(S.loginStatus(JSON.parse(JSON.stringify(login)),date('2026-10-12')).count,7);
assert.equal(S.claimLogin(login,new Date('invalid')).reason,'clock');
const bad=S.normalize({loginDates:['2026-02-30','2026-10-05','2026-10-05','oops'],mailRead:{welcome:true,chapter1:1,'bad':true},welcomeClaimed:'yes'});
assert.equal(bad.loginDates.length,1);
assert.equal(bad.mailRead.welcome,true);
assert.equal(bad.mailRead.chapter1,false);
assert.equal(bad.welcomeClaimed,false);
console.log('PASS services unit: shared mail receipts, read/reload, claim-all, seven login days, clock rollback, malformed migration');
