import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import vm from 'node:vm';
const ctx = {}; vm.createContext(ctx);
vm.runInContext(readFileSync(new URL('../src/runtime/sakurayo-trials.js', import.meta.url), 'utf8'), ctx);
const T = ctx.SakurayoTrials;
assert.deepEqual(JSON.parse(JSON.stringify(T.catalog.map(t => [t.id, t.gate, t.reward]))), [['solo', 2, 120], ['sealed', 3, 180], ['flawless', 4, 240]]);
const mk = (unlock) => ({ coins: 0, unlock, shop40: { ops: {} } });
let s = mk(1);
assert.equal(T.available(s, 'solo'), false);
assert.equal(T.complete(s, 'solo', { win: true, duration: 100 }).reason, 'locked');
s = mk(2);
assert.equal(T.available(s, 'sealed'), false);
assert.equal(T.complete(s, 'solo', { win: false, duration: 50 }).success, false);
assert.equal(s.coins, 0);
let r = T.complete(s, 'solo', { win: true, damageTaken: 30, duration: 200.04 });
assert.equal(r.success, true); assert.equal(r.reward, 120); assert.equal(s.coins, 120); assert.equal(r.best, 200);
r = T.complete(s, 'solo', { win: true, duration: 180 });
assert.equal(r.reward, 0); assert.equal(s.coins, 120); assert.equal(r.best, 180); assert.equal(r.newBest, true);
r = T.complete(s, 'solo', { win: true, duration: 190 });
assert.equal(r.best, 180); assert.equal(r.newBest, false);
s = mk(4);
assert.equal(T.complete(s, 'flawless', { win: true, damageTaken: 1, duration: 100 }).reason, 'hurt');
assert.equal(T.complete(s, 'flawless', { win: true, damageTaken: 0, duration: 100 }).reward, 240);
assert.equal(T.complete(s, 'sealed', { win: true, duration: 90 }).reward, 180);
assert.equal(s.coins, 420);
assert.equal(T.claimable(s), 1);
const n = T.normalize({ receipts: { solo: 1, bogus: 1 }, best: { solo: '12.34', sealed: -1, x: 3 } });
assert.deepEqual(JSON.parse(JSON.stringify(n)), { receipts: { solo: 1 }, best: { solo: 12.3 } });
assert.deepEqual(JSON.parse(JSON.stringify(T.normalize(null))), { receipts: {}, best: {} });
const old = { coins: 5, unlock: 4, shop40: { ops: { pool: 'remnant', trials: 'junk' } } };
T.status(old, 'solo');
assert.equal(old.shop40.ops.pool, 'remnant');
assert.deepEqual(JSON.parse(JSON.stringify(old.shop40.ops.trials)), { receipts: {}, best: {} });
console.log('PASS trials unit: gates, first rewards, fail no reward, best only, flawless, normalize');
