"""Sakurayo BGM composer: writes MIDI programmatically, renders with FluidSynth + FluidR3_GM (MIT),
folds the reverb tail into the loop start for seamless looping, normalizes, encodes OGG.
All music here is original, generated by this script."""
import mido, subprocess, numpy as np, wave, os, sys, random
SF = '/usr/share/sounds/sf2/FluidR3_GM.sf2'
SR = 44100
NOTE = {'C':0,'C#':1,'Db':1,'D':2,'D#':3,'Eb':3,'E':4,'F':5,'F#':6,'Gb':6,'G':7,'G#':8,'Ab':8,'A':9,'A#':10,'Bb':10,'B':11}
def n(s):
    """'D4' -> midi"""
    if s[1:2] in '#b' and len(s) > 2: name, o = s[:2], int(s[2:])
    else: name, o = s[:1], int(s[1:])
    return 12 * (o + 1) + NOTE[name]
QUAL = {'':[0,4,7],'m':[0,3,7],'7':[0,4,7,10],'m7':[0,3,7,10],'maj7':[0,4,7,11],'sus2':[0,2,7],'sus4':[0,5,7],'add9':[0,4,7,14],'madd9':[0,3,7,14],'dim':[0,3,6],'5':[0,7,12]}
def chord(root, q='', octave=3):
    r = 12 * (octave + 1) + NOTE[root]
    return [r + i for i in QUAL[q]]

class Song:
    def __init__(s, bpm, bars, beats=4):
        s.bpm, s.bars, s.beats = bpm, bars, beats
        s.tracks = {}  # ch -> dict(program, events list, cc)
    def track(s, ch, program, vol=100, pan=64, rev=50, cho=0):
        s.tracks[ch] = {'p': program, 'ev': [], 'cc': [(7, vol), (10, pan), (91, rev), (93, cho)]}
        return ch
    def note(s, ch, beat, dur, pitch, vel=80):
        if isinstance(pitch, str): pitch = n(pitch)
        vel = max(1, min(127, int(vel)))
        s.tracks[ch]['ev'].append((beat, dur, pitch, vel))
    def notes(s, ch, beat, dur, pitches, vel=80, strum=0.0):
        for i, p in enumerate(pitches): s.note(ch, beat + i * strum, dur - i * strum, p, vel)
    @property
    def length_beats(s): return s.bars * s.beats
    def seconds(s): return s.length_beats * 60.0 / s.bpm
    def save(s, path, tail_beats=8):
        mf = mido.MidiFile(ticks_per_beat=480)
        meta = mido.MidiTrack(); mf.tracks.append(meta)
        meta.append(mido.MetaMessage('set_tempo', tempo=int(60e6 / s.bpm)))
        meta.append(mido.MetaMessage('end_of_track', time=int((s.length_beats + tail_beats) * 480)))
        for ch, t in s.tracks.items():
            tr = mido.MidiTrack(); mf.tracks.append(tr)
            msgs = []
            if ch != 9: msgs.append((0, 0, mido.Message('program_change', channel=ch, program=t['p'])))
            for c, v in t['cc']: msgs.append((0, 0, mido.Message('control_change', channel=ch, control=c, value=v)))
            for b, d, p, v in t['ev']:
                on = int(round(b * 480)); off = int(round((b + max(d, 0.03)) * 480))
                msgs.append((on, 2, mido.Message('note_on', channel=ch, note=p, velocity=v)))
                msgs.append((off, 1, mido.Message('note_off', channel=ch, note=p, velocity=0)))
            msgs.sort(key=lambda x: (x[0], x[1]))
            last = 0
            for tick, _, m in msgs:
                m.time = tick - last; last = tick; tr.append(m)
        mf.save(path)

def render(song, name, loop=True, rms_db=-17.0, tail=8):
    os.makedirs('out', exist_ok=True)
    mid = f'out/{name}.mid'; wav = f'out/{name}.raw.wav'
    song.save(mid, tail_beats=tail)
    subprocess.run(['fluidsynth', '-ni', '-q', '-F', wav, '-r', str(SR), '-g', '0.6',
                    '-o', 'synth.reverb.room-size=0.75', '-o', 'synth.reverb.width=0.9', '-o', 'synth.reverb.level=0.7',
                    '-o', 'synth.chorus.active=1', SF, mid], check=True, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    with wave.open(wav) as w:
        x = np.frombuffer(w.readframes(w.getnframes()), dtype=np.int16).reshape(-1, 2).astype(np.float32) / 32768
    L = int(round(song.seconds() * SR))
    if loop:
        body = x[:L].copy(); t = x[L:]
        k = min(len(t), len(body)); body[:k] += t[:k]
        # the loop start now already contains the ringing tail, so the seam is continuous
        y = body
    else:
        y = x; nz = np.nonzero(np.abs(y).max(1) > 1e-4)[0]
        y = y[:nz[-1] + int(0.05 * SR)] if len(nz) else y
        fade = int(0.4 * SR); y[-fade:] *= np.linspace(1, 0, fade)[:, None]
    rms = np.sqrt(np.mean(y ** 2)) + 1e-9
    y = y * (10 ** (rms_db / 20) / rms)
    y = np.tanh(y * 1.05) / np.tanh(1.05) * 0.98 if np.abs(y).max() > 0.9 else y
    y = np.clip(y, -0.99, 0.99)
    out = f'out/{name}.wav'
    with wave.open(out, 'wb') as w:
        w.setnchannels(2); w.setsampwidth(2); w.setframerate(SR)
        w.writeframes((y * 32767).astype(np.int16).tobytes())
    os.remove(wav)
    return out, len(y) / SR
